#!/bin/bash
# Pull secrets from 1Password
# Requires: 1Password CLI configured and authenticated

echo "Restoring secrets from 1Password..."

# Create directories
mkdir -p ~/.keys
mkdir -p ~/.aws

# --- API Keys ---
echo "Writing ~/.bashrc.local..."
cat > ~/.bashrc.local << 'EOF'
# Auto-generated by dotfiles bootstrap
# API Keys pulled from 1Password

EOF

# Anthropic API Key
if op read "op://Personal/Anthropic API Key/credential" &>/dev/null; then
    echo "export ANTHROPIC_API_KEY=\"$(op read 'op://Personal/Anthropic API Key/credential')\"" >> ~/.bashrc.local
    echo "  - Anthropic API key restored"
else
    echo "  - Warning: Anthropic API key not found in 1Password"
fi

# GitHub Token
if op read "op://Personal/GitHub PAT MCP/credential" &>/dev/null; then
    echo "export GITHUB_TOKEN=\"$(op read 'op://Personal/GitHub PAT MCP/credential')\"" >> ~/.bashrc.local
    echo "  - GitHub token restored"
else
    echo "  - Warning: GitHub token not found in 1Password"
fi

# --- AWS Credentials ---
echo "Writing ~/.aws/credentials..."
if op read "op://Personal/AWS Credentials/credentials" &>/dev/null; then
    op read "op://Personal/AWS Credentials/credentials" > ~/.aws/credentials
    chmod 600 ~/.aws/credentials
    echo "  - AWS credentials restored"
else
    echo "  - Warning: AWS credentials not found in 1Password"
fi

echo "Writing ~/.aws/config..."
if op read "op://Personal/AWS Credentials/config" &>/dev/null; then
    op read "op://Personal/AWS Credentials/config" > ~/.aws/config
    chmod 600 ~/.aws/config
    echo "  - AWS config restored"
else
    # Create default config
    cat > ~/.aws/config << 'EOF'
[default]
region = us-east-1
output = json
EOF
    echo "  - AWS config created with defaults"
fi

# --- EC2/SSH Keys ---
echo "Restoring EC2 keys to ~/.keys/..."

for key in "playbox-prod-infra.pem" "little-leaps-strapi.pem" "littleleaps-api.pem"; do
    item_name="${key%.pem}"
    if op read "op://Personal/$item_name/private key" &>/dev/null; then
        op read "op://Personal/$item_name/private key" > ~/.keys/$key
        chmod 400 ~/.keys/$key
        echo "  - $key restored"
    else
        echo "  - Warning: $key not found in 1Password"
    fi
done

# Playbox S3 key
if op read "op://Personal/Playbox S3 Key/credential" &>/dev/null; then
    op read "op://Personal/Playbox S3 Key/credential" > ~/.keys/playbox_s3_key.txt
    chmod 600 ~/.keys/playbox_s3_key.txt
    echo "  - playbox_s3_key.txt restored"
else
    echo "  - Warning: Playbox S3 key not found in 1Password"
fi

echo ""
echo "Secrets restoration complete!"
echo "Note: Some items may need to be added to 1Password first."
