#!/usr/bin/ruby
require 'json'
require 'yaml'

source = ARGV[0]
output = ARGV[1]


usage = %(
json2yaml

Convert a json file to a yaml file.

json2yaml <source> <output>
)


begin
  json = File.read(source)
  File.open(output, "w+") { |f| f << JSON.parse(json).to_yaml }
rescue => e
  puts e
  abort usage
end






